server:
  port: 7001

eureka:
  instance:
    hostname: localhost # eureka的服务端实例名称

  server:
    enable-self-preservation: false # eureka的自我保护机制, 默认true开启

  client:
    register-with-eureka: false # false 表示不向注册中心注册自己
    fetch-registry: false # false表示自己端就是注册中心, 我的指责就是维护服务实例, 并不需要去教唆服务
    service-url:
      default-zone: http://${eureka.instance.hostname}:#{server.port}/eureka/ # 单机版服务注册中心

